import { useState } from "react";
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";
import { Send, RefreshCw, Trash2, Award } from "lucide-react";
import confetti from "canvas-confetti";
import jsPDF from "jspdf";

function App() {
  const [idea, setIdea] = useState("");
  const [parsed, setParsed] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showBeforeAfter, setShowBeforeAfter] = useState(false);

  const analyze = async () => {
    if (!idea.trim() || loading) return;
    setLoading(true);
    try {
      const res = await axios.post("https://your-backend.onrender.com/analyze", { idea });
      const result = res.data;
      setParsed(result);
      if (result["Clarity Score (0-100)"] >= 80) {
        confetti({ particleCount: 180, spread: 80, origin: { y: 0.6 } });
      }
    } catch (err) {
      alert("Backend error – is server running on port 5000?");
    } finally {
      setLoading(false);
    }
  };

  const clearAll = () => {
    setIdea("");
    setParsed(null);
    setShowBeforeAfter(false);
  };

  const score = parsed ? Number(parsed["Clarity Score (0-100)"] || 0) : 0;
  const circumference = 2 * Math.PI * 45;
  const offset = circumference - (score / 100) * circumference;


  const generatePDF = () => {
    const doc = new jsPDF();
    let y = 20;
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth() - margin * 2;

    // Strong text cleaner
    const clean = (text) => {
      if (!text) return "";
      return text
        .toString()
        .replace(/[\u2018\u2019\u201C\u201D]/g, '"')     // smart quotes
        .replace(/→/g, "->")
        .replace(/•/g, "-")
        .replace(/[\u2022\u2023]/g, "-")
        .replace(/[\r\n]+/g, " ")
        .trim();
    };

    // Helper to add wrapped text
    const addText = (txt, fontSize = 12, isBold = false) => {
      if (!txt) return;
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      doc.setFontSize(fontSize);

      const cleanTxt = clean(txt);
      const lines = doc.splitTextToSize(cleanTxt, pageWidth);

      lines.forEach((line) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += fontSize === 12 ? 7.5 : 10;
      });
      y += 5;
    };

    // === PDF Content ===
    doc.setFontSize(22);
    doc.text("Explain My Plan", margin, y);
    doc.setFontSize(12);
    doc.text("Structured Output by KALNET AI", margin, y + 12);
    y += 30;

    doc.setFontSize(16);
    doc.text(`Clarity Score: ${score}/100`, margin, y);
    y += 20;

    addText("Goal:", 14, true);
    addText(parsed.Goal);

    addText("Method / Approach:", 14, true);
    addText(parsed.Method);

    addText("Timeline:", 14, true);
    addText(parsed.Timeline);

    addText("Simplified Version:", 14, true);
    addText(parsed["Simplified Version"]);

    // Steps
    addText("Steps:", 14, true);
    parsed.Steps?.forEach((step, i) => {
      addText(`${i + 1}. ${step}`);
    });

    // Missing Elements
    addText("Missing Elements:", 14, true);
    parsed["Missing Elements"]?.forEach((item) => addText(`• ${item}`));

    // Actionable Next Steps
    addText("Actionable Next Steps:", 14, true);
    parsed["Actionable Next Steps"]?.forEach((step) => {
      addText(`→ ${step}`);
    });

    // Footer
    doc.setFontSize(10);
    doc.text("Generated by Explain My Plan — KALNET Intern Assignment", margin, 285);

    doc.save(`My-Structured-Plan-${Date.now()}.pdf`);
  };
  return (
    <div className="min-h-screen bg-grid bg-gradient-to-br from-zinc-50 via-white to-indigo-50 overflow-hidden">
      {/* Navbar */}
      <nav className="bg-white/90 backdrop-blur-lg border-b sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-6 py-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-indigo-600 to-teal-500 rounded-2xl flex items-center justify-center text-white font-bold text-3xl shadow-inner">E</div>
            <h1 className="text-3xl font-semibold tracking-tighter text-zinc-900">Explain My Plan</h1>
          </div>
          <p className="text-sm font-medium text-zinc-500">AI Clarity Tool</p>
        </div>
      </nav>

      <div className="max-w-5xl mx-auto px-6 py-12">
        {/* Input Section */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass border border-zinc-200/80 rounded-3xl p-10 shadow-2xl"
        >
          <h2 className="text-3xl font-semibold mb-6 text-zinc-900">Share your idea</h2>
          <textarea
            rows={7}
            placeholder="I want to start a YouTube channel and earn money quickly..."
            value={idea}
            onChange={(e) => setIdea(e.target.value)}
            className="w-full resize-none border border-zinc-200 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100 rounded-3xl p-8 text-lg placeholder-zinc-400 transition-all duration-300"
          />

          <div className="flex gap-4 mt-8">
            <motion.button
              whileHover={{ scale: 1.04 }}
              whileTap={{ scale: 0.96 }}
              onClick={analyze}
              disabled={loading || !idea.trim()}
              className="flex-1 bg-gradient-to-r from-indigo-600 to-teal-600 hover:from-indigo-700 hover:to-teal-700 text-white font-semibold py-5 rounded-3xl flex items-center justify-center gap-3 shadow-lg disabled:opacity-50 transition-all"
            >
              {loading ? (
                <>Analyzing with AI <RefreshCw className="animate-spin" size={22} /></>
              ) : (
                <>Analyze My Plan <Send size={22} /></>
              )}
            </motion.button>

            <motion.button
              whileHover={{ scale: 1.08 }}
              whileTap={{ scale: 0.95 }}
              onClick={clearAll}
              className="px-10 bg-white border-2 border-zinc-300 hover:border-red-400 text-zinc-700 rounded-3xl flex items-center gap-3 font-medium"
            >
              <Trash2 size={22} /> Clear
            </motion.button>
          </div>
        </motion.div>

        {/* Results Section */}
        <AnimatePresence>
          {parsed && (
            <motion.div
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              className="mt-16"
            >
              <div className="flex justify-between items-center mb-10">
                <h2 className="text-4xl font-semibold text-zinc-900">Your Structured Plan</h2>
                <button
                  onClick={() => setShowBeforeAfter(!showBeforeAfter)}
                  className="text-indigo-600 hover:text-indigo-700 font-medium flex items-center gap-2 underline-offset-4 hover:underline"
                >
                  {showBeforeAfter ? "Hide Comparison" : "Show Before vs After"}
                </button>
              </div>

              {showBeforeAfter && (
                <div className="grid md:grid-cols-2 gap-8 mb-12">
                  <div className="glass p-8 rounded-3xl border">Your Original Idea<p className="mt-4 text-zinc-700 leading-relaxed">{idea}</p></div>
                  <div className="glass p-8 rounded-3xl border border-teal-200">
                    Simplified Version<p className="mt-4 text-zinc-700 leading-relaxed">{parsed["Simplified Version"]}</p>
                  </div>
                </div>
              )}

              {/* Clarity Score */}
              <div className="flex justify-center mb-16">
                <div className="relative w-52 h-52">
                  <svg className="w-52 h-52 -rotate-90" viewBox="0 0 100 100">
                    <circle cx="50" cy="50" r="45" fill="none" stroke="#e5e7eb" strokeWidth="9" />
                    <motion.circle
                      cx="50" cy="50" r="45"
                      fill="none"
                      stroke="#4F46E5"
                      strokeWidth="9"
                      strokeDasharray={circumference}
                      strokeDashoffset={offset}
                      initial={{ strokeDashoffset: circumference }}
                      animate={{ strokeDashoffset: offset }}
                      transition={{ duration: 1.5, ease: "easeOut" }}
                    />
                  </svg>
                  <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <Award className="text-indigo-600 mb-2" size={38} />
                    <div className="text-7xl font-bold text-zinc-900 tracking-tighter">{score}</div>
                    <div className="text-sm -mt-1 tracking-widest text-zinc-500">CLARITY</div>
                  </div>
                </div>
              </div>

              {/* Cards with Floating Hover Effect */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {[
                  { title: "Goal", value: parsed.Goal, color: "border-indigo-200" },
                  { title: "Method", value: parsed.Method, color: "border-teal-200" },
                  { title: "Timeline", value: parsed.Timeline, color: "border-amber-200" },
                  { title: "Simplified Version", value: parsed["Simplified Version"], color: "border-teal-200" },
                ].map((item, i) => (
                  <motion.div
                    key={i}
                    whileHover={{ y: -12, scale: 1.02, transition: { type: "spring", stiffness: 300 } }}
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.08 }}
                    className={`glass border ${item.color} rounded-3xl p-9 shadow-xl hover:shadow-2xl`}
                  >
                    <h3 className="font-semibold text-xl mb-4 text-zinc-800">{item.title}</h3>
                    <p className="text-zinc-700 leading-relaxed">{item.value}</p>
                  </motion.div>
                ))}

                {/* Steps & Other Cards (also floating) */}
                <motion.div
                  whileHover={{ y: -12, scale: 1.02 }}
                  className="glass border border-indigo-200 rounded-3xl p-9 shadow-xl hover:shadow-2xl md:col-span-2"
                >
                  <h3 className="font-semibold text-xl mb-6">Steps</h3>
                  <ul className="space-y-5">
                    {parsed.Steps?.map((step, i) => (
                      <li key={i} className="flex gap-5 items-start">
                        <div className="w-8 h-8 bg-indigo-100 text-indigo-600 rounded-2xl flex items-center justify-center font-bold flex-shrink-0">{i + 1}</div>
                        <p className="text-zinc-700 pt-1">{step}</p>
                      </li>
                    ))}
                  </ul>
                </motion.div>

                <motion.div
                  whileHover={{ y: -12, scale: 1.02 }}
                  className="glass border border-red-200 bg-red-50/70 rounded-3xl p-9 shadow-xl hover:shadow-2xl"
                >
                  <h3 className="font-semibold text-xl mb-5 text-red-700">Missing Elements</h3>
                  <ul className="space-y-4 text-red-700">
                    {parsed["Missing Elements"]?.map((item, i) => <li key={i}>• {item}</li>)}
                  </ul>
                </motion.div>

                <motion.div
                  whileHover={{ y: -12, scale: 1.02 }}
                  className="glass border border-teal-200 rounded-3xl p-9 shadow-xl hover:shadow-2xl"
                >
                  <h3 className="font-semibold text-xl mb-5">Actionable Next Steps</h3>
                  <ul className="space-y-5">
                    {parsed["Actionable Next Steps"]?.map((step, i) => (
                      <li key={i} className="flex gap-4 text-zinc-700">→ {step}</li>
                    ))}
                  </ul>
                </motion.div>
              </div>
              {/* PDF Export Button */}
              <motion.button
                whileHover={{ scale: 1.05 }}
                onClick={generatePDF}
                className="mx-auto flex items-center gap-3 bg-gradient-to-r from-teal-600 to-indigo-600 text-white px-10 py-4 rounded-3xl font-medium shadow-xl"
              >
                📄 Download Full Plan as PDF
              </motion.button>
              {/* Re-analyze Button */}
              <motion.button
                whileHover={{ scale: 1.05, y: -2 }}
                onClick={analyze}
                className="mt-14 mx-auto flex items-center gap-4 bg-zinc-900 hover:bg-black text-white px-12 py-5 rounded-3xl font-medium text-lg shadow-xl"
              >
                <RefreshCw size={24} /> Re-analyze Plan
              </motion.button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

export default App;
